apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: sharded-statefulset-redis
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: sharded-statefulset-redis