apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sharded-statefulset-redis
spec:
  selector:
    matchLabels:
      app: sharded-statefulset-redis
  serviceName: "redis" # This should match the metadata.name of the headless service
  replicas: 2
  template:
    metadata:
      labels:
        app: sharded-statefulset-redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
          name: redis