apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: kuard-rs-prod
    version: "2"
  name: kuard-rs-private-reg-amd64
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuard-rs-prod
      version: "2"
  template:
    metadata:
      labels:
        app: kuard-rs-prod
        version: "2"
    spec:
      containers:
        - name: kuard-container
          image: dhrsharm.azurecr.io/kuar-demo/kuard:blue-amd64
          ports:
          - containerPort: 3000
            protocol: TCP
            name: http
      imagePullSecrets:
      - name: dhrsharm-cr-secret